#!/usr/bin/env bash
set -euo pipefail

SCRIPT_PATH="$(realpath "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"

# Walk up until we find RFantibody
ROOTDIR="$SCRIPT_DIR"
while [[ "$ROOTDIR" != "/" && "$(basename "$ROOTDIR")" != "RFantibody" ]]; do
  ROOTDIR="$(dirname "$ROOTDIR")"
done

if [[ "$(basename "$ROOTDIR")" != "RFantibody" ]]; then
  echo "Error: Could not locate RFantibody root directory."
  exit 1
fi

# Auto-generated by: scripts/util/make_patch_quiver_script.sh
# framework: ./inputs/framework/processed/8coh_HLT.pdb
# target:    inputs/target/processed/CD33_7AW6_processed_chains_A.pdb
# patch:     A218,A219,A220
# threshold: 1.75
# start:     A148
mkdir -p $(dirname ./scripts/rfantibody_jobs/logs/quiver_8coh_HLT__CD33_7AW6_processed_chains_A__T1.75__A218_A219_A220_.log)
touch ./scripts/rfantibody_jobs/logs/quiver_8coh_HLT__CD33_7AW6_processed_chains_A__T1.75__A218_A219_A220_.log
nohup bash "$ROOTDIR/scripts/pipeline_rfantibody.sh" \
  --n-designs 10 --n-seqs 10 --n-recycles 10 --cuda-device 3 \
  --design-loops "H1:7,H2:5-7,H3:6-19" \
  -f "./inputs/framework/processed/8coh_HLT.pdb" \
  -t "inputs/target/processed/CD33_7AW6_processed_chains_A.pdb" \
  --hotspots "A218,A219,A220" \
  > "./scripts/rfantibody_jobs/logs/quiver_8coh_HLT__CD33_7AW6_processed_chains_A__T1.75__A218_A219_A220_.log" 2>&1
