#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  bash scripts/util/make_patch_quiver_script.sh -f <framework.pdb> -t <target_processed.pdb> -T <threshold> [-S A148]

Generates one runnable script per hotspot triplet patch into:
  RFantibody/scripts/quiver_jobs/

Patch criteria:
- same chain
- residues increasing
- gaps: (r2-r1)<=2 and (r3-r2)<=2
- RSA sum: rsa(r1)+rsa(r2)+rsa(r3) >= THRESHOLD
- optional start filter: ignore residues before CHAINSTART (e.g. A148) on that chain only
EOF
  exit 2
}

framework=""
target=""
start_spec=""
threshold=""
CUDA=0
while getopts ":f:t:S:T:h:c:" opt; do
  case "$opt" in
    f) framework="$OPTARG" ;;
    t) target="$OPTARG" ;;
    S) start_spec="$OPTARG" ;;
    T) threshold="$OPTARG" ;;
    c) CUDA="$OPTARG" ;;
    h) usage ;;
    \?) usage ;;
    :) usage ;;
  esac
done

[[ -n "$framework" ]] || usage
[[ -n "$target"    ]] || usage
[[ -n "$threshold" ]] || usage
[[ -f "$framework" ]] || { echo "ERROR: framework not found: $framework" >&2; exit 2; }
[[ -f "$target"    ]] || { echo "ERROR: target not found: $target" >&2; exit 2; }

# validate threshold is numeric
gawk -v T="$threshold" 'BEGIN{ if (T+0 != T) exit 1 }' || { echo "ERROR: -T must be numeric (e.g. 1.5)" >&2; exit 2; }

OUTDIR="./scripts/quiver_jobs"
LOGDIR="$OUTDIR/logs"
mkdir -p "$OUTDIR" "$LOGDIR"

# basenames without extensions
fw_base="$(basename "$framework")"; fw_base="${fw_base%.*}"
tg_base="$(basename "$target")";    tg_base="${tg_base%.*}"

sanitize() {
  printf "%s" "$1" \
  | sed -E 's/[^A-Za-z0-9._-]+/_/g; s/^_+//; s/_+$//; s/_+/_/g'
}


fw_tag="$(sanitize "$fw_base")"
tg_tag="$(sanitize "$tg_base")"

# ---- Find patches from REMARK 900 hotspot lines, with RSA filtering ----
patches="$(
gawk -v START_SPEC="$start_spec" -v THRESHOLD="$threshold" '
  BEGIN {
    if (START_SPEC != "") {
      if (match(START_SPEC, /^([A-Za-z])([0-9]+)$/, m)) {
        start_chain = m[1]
        start_res   = m[2] + 0
        has_start   = 1
      } else {
        print "ERROR: start spec must look like A148" > "/dev/stderr"
        exit 2
      }
    } else {
      has_start = 0
    }
  }

  # Match lines like:
  # REMARK 900 P A150 rsa=0.4706 asa=64.00
  $1=="REMARK" && $2=="900" && $3 ~ /^[A-Z]$/ && $4 ~ /^[A-Za-z][0-9]+/ {
    chain = substr($4, 1, 1)
    res   = substr($4, 2) + 0

    if (has_start && chain == start_chain && res < start_res) next

    # Extract rsa=...
    rsa = ""
    if (match($0, /rsa=([0-9]*\.[0-9]+|[0-9]+)/, rm)) {
      rsa = rm[1] + 0.0
    } else {
      next
    }

    key = chain SUBSEP res
    if (!seen[key]++) {
      count[chain]++
      arr[chain, count[chain]] = res
    }
    rsa_map[chain, res] = rsa
  }

  END {
    for (chain in count) {
      n = count[chain]

      delete tmp
      for (i=1; i<=n; i++) tmp[i] = arr[chain, i]

      delete ord
      asorti(tmp, ord, "@val_num_asc")

      delete reslist
      for (i=1; i<=n; i++) reslist[i] = tmp[ ord[i] ]

      for (i=1; i<=n-2; i++) {
        r1 = reslist[i]
        for (j=i+1; j<=n-1; j++) {
          r2 = reslist[j]
          if (r2 - r1 > 2) break
          for (k=j+1; k<=n; k++) {
            r3 = reslist[k]
            if (r3 - r2 > 2) break

            s = rsa_map[chain, r1] + rsa_map[chain, r2] + rsa_map[chain, r3]
            if (s + 1e-12 >= THRESHOLD) {
              printf "%s%d,%s%d,%s%d\n", chain, r1, chain, r2, chain, r3
            }
          }
        }
      }
    }
  }
' "$target"
)"

if [[ -z "$patches" ]]; then
  echo "No hotspot patches found (after RSA thresholding) in: $target" >&2
  exit 0
fi

# ---- Generate one script per patch ----
n=0
while IFS= read -r patch; do
  [[ -n "$patch" ]] || continue
  ((n++)) || true

  patch_slug="$(echo "$patch" | tr ',' '_' | tr -c 'A-Za-z0-9_-' '_' | sed 's/__\+/_/g')"

  script_path="${OUTDIR}/run_quiver_${fw_tag}__${tg_tag}__T${threshold}__${patch_slug}.sh"
  log_path="${LOGDIR}/quiver_${fw_tag}__${tg_tag}__T${threshold}__${patch_slug}.log"

  cat > "$script_path" <<EOF
#!/usr/bin/env bash
set -euo pipefail

SCRIPT_PATH="\$(realpath "\${BASH_SOURCE[0]}")"
SCRIPT_DIR="\$(dirname "\$SCRIPT_PATH")"

# Walk up until we find RFantibody
ROOTDIR="\$SCRIPT_DIR"
while [[ "\$ROOTDIR" != "/" && "\$(basename "\$ROOTDIR")" != "RFantibody" ]]; do
  ROOTDIR="\$(dirname "\$ROOTDIR")"
done

if [[ "\$(basename "\$ROOTDIR")" != "RFantibody" ]]; then
  echo "Error: Could not locate RFantibody root directory."
  exit 1
fi

# Auto-generated by: scripts/util/make_patch_quiver_script.sh
# framework: $framework
# target:    $target
# patch:     $patch
# threshold: $threshold
# start:     ${start_spec:-<none>}
mkdir -p \$(dirname $log_path)
touch $log_path
nohup bash "\$ROOTDIR/scripts/test_pipeline_quiver.sh" \\
  -d 25 -n 10 -r 10 -c $CUDA \\
  -l "H1:7,H2:5-7,H3:6-19" \\
  -f "$framework" \\
  -t "$target" \\
  -h "$patch" \\
  > "$log_path" 2>&1
EOF

  chmod +x "$script_path"
done <<< "$patches"

echo "Generated ${n} scripts in: ${OUTDIR}"
echo "Logs will go to: ${LOGDIR}"
