#!/usr/bin/env bash
set -euo pipefail

SCRIPT_PATH="$(realpath "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"

# Walk up until we find RFantibody
ROOTDIR="$SCRIPT_DIR"
while [[ "$ROOTDIR" != "/" && "$(basename "$ROOTDIR")" != "RFantibody" ]]; do
  ROOTDIR="$(dirname "$ROOTDIR")"
done

if [[ "$(basename "$ROOTDIR")" != "RFantibody" ]]; then
  echo "Error: Could not locate RFantibody root directory."
  exit 1
fi

# Auto-generated by: scripts/util/make_patch_quiver_script.sh
# framework: /home/user/RFantibody/data/02_intermediate/framework/7xl0_HLT.pdb
# target:    /home/user/RFantibody/data/02_intermediate/target/CD33_7AW6_A_processed.pdb
# patch:     A148,A150,A152
# threshold: 1.75
# start:     A148
mkdir -p $(dirname /home/user/RFantibody/data/03_jobs/run_cd33_7xl0_A148/jobs/logs/job__fw7xl0_HLT__tgCD33_7AW6_A_processed__T1.75__hsA148_A150_A152_.log)
touch /home/user/RFantibody/data/03_jobs/run_cd33_7xl0_A148/jobs/logs/job__fw7xl0_HLT__tgCD33_7AW6_A_processed__T1.75__hsA148_A150_A152_.log
nohup bash "$ROOTDIR/scripts/pipeline_rfantibody.sh" \
  --n-designs 10 --n-seqs 10 --n-recycles 10 --cuda-device 0 \
  --design-loops H1:7,H2:5-7,H3:6-19 \
  -f "/home/user/RFantibody/data/02_intermediate/framework/7xl0_HLT.pdb" \
  -t "/home/user/RFantibody/data/02_intermediate/target/CD33_7AW6_A_processed.pdb" \
  --hotspots "A148,A150,A152" \
  --results-dir data/04_results/run_cd33_7xl0_A148/ \
  > "/home/user/RFantibody/data/03_jobs/run_cd33_7xl0_A148/jobs/logs/job__fw7xl0_HLT__tgCD33_7AW6_A_processed__T1.75__hsA148_A150_A152_.log" 2>&1
