frameworks:
  3eak:
    pdb_id: "3EAK"
    sabdab_chothia_url: "https://opig.stats.ox.ac.uk/webapps/sabdab-sabpred/sabdab/pdb/3eak/?scheme=chothia"
    kind: "nanobody"          # nanobody or antibody
    chain: "A"
  7eow:
    pdb_id: "7EOW"
    sabdab_chothia_url: "https://opig.stats.ox.ac.uk/webapps/sabdab-sabpred/sabdab/pdb/7eow/?scheme=chothia"
    kind: "nanobody"          # nanobody or antibody
    chain: "B"
  7xl0:
    pdb_id: "7XL0"
    sabdab_chothia_url: "https://opig.stats.ox.ac.uk/webapps/sabdab-sabpred/sabdab/pdb/7xl0/?scheme=chothia"
    kind: "nanobody"
    chain: "A"
  8coh:
    pdb_id: "8COH"
    sabdab_chothia_url: "https://opig.stats.ox.ac.uk/webapps/sabdab-sabpred/sabdab/pdb/8coh/?scheme=chothia"
    kind: "nanobody"
    chain: "A"
  8z8v:
    pdb_id: "8Z8V"
    sabdab_chothia_url: "https://opig.stats.ox.ac.uk/webapps/sabdab-sabpred/sabdab/pdb/8z8v/?scheme=chothia"
    kind: "nanobody"
    chain: "B"
  

targets:
  # EXPLICIT TARGET "duplication" to avoid further shenanigans downstream with "processed_chains"
  # This was done on purpose due to limitations in wildcards and chain tags handling downstream
  # EXPLICIT "save_filename" field definition for the same purpouses
  CD33_7AW6_A:
    target_name: "CD33"
    pdb_id: "7AW6"
    save_filename: "CD33_7AW6.pdb"
    processed_filename: "CD33_7AW6_A_processed.pdb"
    rcsb_pdb_url: "https://files.rcsb.org/download/7AW6.pdb"
    chains: "A"
    ligands: "NAG,FVP"
    cutoff: 4.0
    run_dssp: true
    dssp_threshold: 0.4
    renumber: false
    format: "qv"

  CD33_7AW6_B:
    target_name: "CD33"
    pdb_id: "7AW6"
    save_filename: "CD33_7AW6.pdb"
    rcsb_pdb_url: "https://files.rcsb.org/download/7AW6.pdb"
    chains: "B"
    ligands: "NAG,FVP"
    cutoff: 4.0
    run_dssp: true
    dssp_threshold: 0.4
    renumber: false
    format: "qv"

  CD33_7AW6_AB:
    target_name: "CD33"
    pdb_id: "7AW6"
    save_filename: "CD33_7AW6.pdb"
    rcsb_pdb_url: "https://files.rcsb.org/download/7AW6.pdb"
    chains: "B"
    ligands: "NAG,FVP"
    cutoff: 4.0
    run_dssp: true
    dssp_threshold: 0.4
    renumber: false
    format: "qv"

experiments:
  # This experiment is for 7AW6, starts at res A148,
  # Takes RSA 1.75 as threshold, 10 designs (10 sequences per)
  7AW6_A_startA148_rsa1p75_nd10_ns10:
  # mostly defined by framework (fw), target (hs), hotspot patch (hs)
    format: "qv"
    design_loops: "H1:7,H2:5-7,H3:6-19"
    diffuser_t: 50 # minimum of T=15 for debugging; 50 normally
    n_designs: 15 # 15 designs per fw-tg-hs
    n_seqs: 10
    n_recycles: 10
    hotspot_prop: 0.2
    rsa_threshold: 1.75 # Sum RSA over 3 residues as available patch
    start_spec: "A148" # start residue (we do A148 for C chain)
  # cuda_device: Not specified (should specify if using Vertex)

  # Config with minimal N parameters for debugging
  debug_run_config:
    format: "qv"
    design_loops: "H1:7,H2:6,H3:10"
    diffuser_t: 15 # minimum of T=15 (rfab constraint) for debugging; 50 normally
    n_designs: 1
    n_seqs: 1
    n_recycles: 1
    hotspot_prop: 0.2
    rsa_threshold: 2 # Sum RSA over 3 residues as available patch
    start_spec: "A190" # start residue (we do A148 for C chain)
  # cuda_device: Not specified (should specify if using Vertex)

    

runs:
  sample_run_7eow:
    framework_id: "7eow"
    target_id: "CD33_7AW6_A"
    experiment: "debug_run_config"
    n_jobs: 5

  sample_run_3eak:
    framework_id: "3eak"
    target_id: "CD33_7AW6_A"
    experiment: "debug_run_config"
    n_jobs: 5

  run_cd33_7eow_A148:
    framework_id: "7eow"
    target_id: "CD33_7AW6_A"
    experiment: "7AW6_A_startA148_rsa1p75_nd10_ns10"
    n_jobs: 5

  run_cd33_3eak_A148:
    framework_id: "3eak"
    target_id: "CD33_7AW6_A"
    experiment: "7AW6_A_startA148_rsa1p75_nd10_ns10"
    n_jobs: 5

  run_cd33_7xl0_A148:
    framework_id: "7xl0"
    target_id: "CD33_7AW6_A"
    experiment: "7AW6_A_startA148_rsa1p75_nd10_ns10"
    n_jobs: 5

  run_cd33_8coh_A148:
    framework_id: "8coh"
    target_id: "CD33_7AW6_A"
    experiment: "7AW6_A_startA148_rsa1p75_nd10_ns10"
    n_jobs: 5

  run_cd33_8z8v_A148:
    framework_id: "8z8v"
    target_id: "CD33_7AW6_A"
    experiment: "7AW6_A_startA148_rsa1p75_nd10_ns10"
    n_jobs: 5