from utils import get_run_cfg, get_exp_cfg
#########################################
# generate hotspot patches (patch scripts)
#########################################


rule generate_patches:
    input:
        framework=lambda wildcards: f"data/02_intermediate/framework/{get_run_cfg(wildcards.run_id, config)['framework_id']}_HLT.pdb",
        target=lambda wildcards: f"data/02_intermediate/target/{get_run_cfg(wildcards.run_id, config)['target_id']}_processed.pdb",
        generator=local("scripts/util/make_patch_args.sh"),
    output:
        run_config="data/03_jobs/{run_id}/run_config.yaml",
        jobs_dir=directory("data/03_jobs/{run_id}/jobs"),
        manifest="data/03_jobs/{run_id}/jobs_list.tsv",
    resources:
        googlebatch_job_name=lambda wc: f"rfab-{wc.run_id}-generate_patch",
    params:
        results_dir=directory("data/04_rfab/{run_id}"),
        rsa_threshold=lambda wildcards: str(get_exp_cfg(wildcards.run_id, config).get("rsa_threshold", 0.2)),
        design_loops=lambda wildcards: str(get_exp_cfg(wildcards.run_id, config).get("design_loops", "")),
        start_spec=lambda wildcards: str(get_exp_cfg(wildcards.run_id, config).get("start_spec", "")),
        loops_arg=lambda wc: (f'-L "{get_exp_cfg(wc.run_id, config).get("design_loops")}"' if get_exp_cfg(wc.run_id, config).get("design_loops") else ""),
        start_arg=lambda wc: (f'-S "{get_exp_cfg(wc.run_id, config).get("start_spec")}"' if get_exp_cfg(wc.run_id, config).get("start_spec") else ""),
        n_designs=lambda wildcards: str(get_exp_cfg(wildcards.run_id, config).get("n_designs", 10)),
        n_seqs=lambda wildcards: str(get_exp_cfg(wildcards.run_id, config).get("n_seqs", 10)),
        n_recycles=lambda wildcards: str(get_exp_cfg(wildcards.run_id, config).get("n_recycles", 10)),
        cuda_device=lambda wildcards: str(get_exp_cfg(wildcards.run_id, config).get("cuda_device", 0)),
        res_format=lambda wildcards: str(get_exp_cfg(wildcards.run_id, config).get("format", "qv")),
        diffuser_t=lambda wildcards: str(get_exp_cfg(wildcards.run_id, config).get("diffuser_t", 50))
    params:
        rsa_threshold=lambda wc: str(get_exp_cfg(wc.run_id, config).get("rsa_threshold", 0.2)),
        design_loops=lambda wc: str(get_exp_cfg(wc.run_id, config).get("design_loops", "")),
        start_spec=lambda wc: str(get_exp_cfg(wc.run_id, config).get("start_spec", "")),
        n_designs=lambda wc: str(get_exp_cfg(wc.run_id, config).get("n_designs", 10)),
        n_seqs=lambda wc: str(get_exp_cfg(wc.run_id, config).get("n_seqs", 10)),
        n_recycles=lambda wc: str(get_exp_cfg(wc.run_id, config).get("n_recycles", 10)),
        cuda_device=lambda wc: str(get_exp_cfg(wc.run_id, config).get("cuda_device", 0)),
        res_format=lambda wc: str(get_exp_cfg(wc.run_id, config).get("format", "qv")),
        diffuser_t=lambda wc: str(get_exp_cfg(wc.run_id, config).get("diffuser_t", 50)),
    run:
        import os, yaml
        from datetime import datetime as dt
        from snakemake.shell import shell

        os.makedirs(output.jobs_dir, exist_ok=True)
        # Save the run configuration to a log file in the jobs directory
        timestamp = dt.now().strftime("%y%m%d_%H%M%S")
        run_id = wildcards.run_id
        payload = {
            "timestamp": timestamp,
            "run_id": run_id,
            "exp_id": config['runs'][run_id]['experiment'],
            "run_config": get_run_cfg(run_id, config),
            "exp_config": get_exp_cfg(run_id, config),
        }
        with open(output.run_config, "w", encoding="utf-8") as f:
            f.write(f'{"#"*30}\n')
            f.write("# RFantibody run configuration\n")
            f.write("# Autogenerated from Snakemake\n")
            yaml.safe_dump(payload, f, sort_keys=False)

        # Generation part: Calls the refactored make_patch_args.sh
        shell(r"""
        set -euo pipefail

        JOBS_DIR="{output.jobs_dir}"
        mkdir -p "$JOBS_DIR/logs"

        RESULTS_DIR={params.results_dir}

        GEN="$(realpath "{input.generator}")"

        GEN_ARGS=( -f "{input.framework}" -t "{input.target}" -T "{params.rsa_threshold}" -O "$JOBS_DIR" -R "$RESULTS_DIR" )
        GEN_ARGS+=( -c "{params.cuda_device}" -d "{params.n_designs}" -s "{params.n_seqs}" -r "{params.n_recycles}" )
        GEN_ARGS+=( -F "{params.res_format}" --diffuser-t "{params.diffuser_t}" )

        if [[ -n "{params.design_loops}" ]]; then
          GEN_ARGS+=( -L "{params.design_loops}" )
        fi
        if [[ -n "{params.start_spec}" ]]; then
          GEN_ARGS+=( -S "{params.start_spec}" )
        fi

        bash "$GEN" "${{GEN_ARGS[@]}}"

        # Writes manifest
        : > "{output.manifest}"
        for p in "$JOBS_DIR"/*.args; do
          [[ -e "$p" ]] || break
          printf "%s\n" "$(basename "$p")" >> "{output.manifest}"
        done

        if [[ ! -s "{output.manifest}" ]]; then
          echo "ERROR: no args files generated (manifest empty): {output.manifest}" >&2
          ls -lah "$JOBS_DIR" >&2 || true
          exit 2
        fi
        """)
