from utils import get_run_cfg, get_exp_cfg
#########################################
# generate hotspot patches (patch scripts)
#########################################


rule generate_patches:
    input:
        framework=lambda wildcards: f"data/02_intermediate/framework/{get_run_cfg(wildcards.run_id, config)['framework_id']}_HLT.pdb",
        target=lambda wildcards: f"data/02_intermediate/target/{get_run_cfg(wildcards.run_id, config)['target_id']}_processed.pdb",
        generator="scripts/util/make_patch_pipeline_script.sh"
    output:
        run_config="data/03_jobs/{run_id}/run_config.yaml",
        patches_dir=directory("data/03_jobs/{run_id}/jobs"),
        manifest="data/03_jobs/{run_id}/jobs_list.tsv"
    params:
        patches_dir=directory("data/03_jobs/{run_id}/jobs"),
        results_dir=directory("data/04_results/{run_id}/"),
        rsa_threshold=lambda wildcards: str(get_exp_cfg(wildcards.run_id, config).get("rsa_threshold", 0.2)),
        design_loops=lambda wildcards: str(get_exp_cfg(wildcards.run_id, config).get("design_loops", "")),
        start_spec=lambda wildcards: str(get_exp_cfg(wildcards.run_id, config).get("start_spec", "")),
        loops_arg=lambda wc: (f'-L "{get_exp_cfg(wc.run_id, config).get("design_loops")}"' if get_exp_cfg(wc.run_id, config).get("design_loops") else ""),
        start_arg=lambda wc: (f'-S "{get_exp_cfg(wc.run_id, config).get("start_spec")}"' if get_exp_cfg(wc.run_id, config).get("start_spec") else ""),
        n_designs=lambda wildcards: str(get_exp_cfg(wildcards.run_id, config).get("n_designs", 10)),
        n_seqs=lambda wildcards: str(get_exp_cfg(wildcards.run_id, config).get("n_seqs", 10)),
        n_recycles=lambda wildcards: str(get_exp_cfg(wildcards.run_id, config).get("n_recycles", 10)),
        cuda_device=lambda wildcards: str(get_exp_cfg(wildcards.run_id, config).get("cuda_device", 0)),
        format=lambda wildcards: str(get_exp_cfg(wildcards.run_id, config).get("format", "qv"))
    run:
        import os
        import yaml
        from snakemake.shell import shell
        from datetime import datetime as dt
        os.makedirs(output.patches_dir, exist_ok=True)
        # Saving run config to know which we are writing to
        timestamp = dt.now().strftime("%y%m%d_%H%M%S")
        run_id = wildcards.run_id
        run_config = get_run_cfg(run_id, config)
        exp_config = get_exp_cfg(run_id, config)
        payload = {"timestamp": timestamp,
                   "run_id": run_id,
                   "run_config": run_config,
                   "exp_config": exp_config,
        }
        with open(output.run_config, "w", encoding="utf-8") as f:
            f.write(f'{"#"*30}\n')
            f.write("# RFantibody run configuration\n")
            f.write("# Autogenerated from Snakemake\n")
            f.write(f"# Run ID: {run_id}")
            yaml.safe_dump(payload, f, sort_keys=False)

        shell(r"""
        set -euo pipefail
        echo {output}
        mkdir -p {output.patches_dir}

        # Run generator inside run-specific folder so it doesn't collide with other runs
        TG="$(realpath "{input.target}")"
        FW="$(realpath "{input.framework}")"
        GEN="$(realpath "{input.generator}")"
        # cd "{output.patches_dir}"

        bash "$GEN" -f "$FW" -t "$TG" -T "{params.rsa_threshold}" -c "{params.cuda_device}" -d "{params.n_designs}" -s "{params.n_seqs}" -r "{params.n_recycles}" -O "{params.patches_dir}" -R {params.results_dir} {params.loops_arg} {params.start_arg}

        if [ ! -d {output.patches_dir} ]; then
          echo "ERROR: generator did not create {output.patches_dir}" >&2
          exit 2
        fi
        # Generator writes into job directory

        # Write manifest
        : > "{output.manifest}"
        for s in {params.patches_dir}/*.sh; do
          [ -e "$s" ] || break
          printf "%s\t%s\n" "$(realpath "$s")" >> "{output.manifest}"
        done

        # Sanity
        if [ ! -s "{output.manifest}" ]; then
          echo "ERROR: no patch scripts generated (manifest empty): {output.manifest}" >&2
          exit 2
        fi
        """)
